# config.py — Paramètres de configuration

# LIDAR
LIDAR_PORT = "/dev/ttyUSB0"
LIDAR_BAUDRATE = 256000
LIDAR_SCAN_TYPE = "express"

LIDAR_IGNORE_INTERIOR_SECTOR = False
LIDAR_INTERIOR_MIN_DEG = 90
LIDAR_INTERIOR_MAX_DEG = 270

# PROPULSION
DIRECTION_PROP = 1
PWM_STOP_PROP = 7.36
POINT_MORT_PROP = 0.37
DELTA_PWM_MAX_PROP = 1.0
VITESSE_MAX_M_S_HARD = 8.0
VITESSE_MAX_M_S_SOFT = 1.5

# DIRECTION
DIRECTION_DIR = 1
ANGLE_PWM_MIN = 4.5
ANGLE_PWM_MAX = 8.0
ANGLE_PWM_CENTRE = 6.25
ANGLE_DEGRE_MAX = 18

# CONDUITE AUTONOME
L_ENTRAXE_M = 0.180
W_EMPATTEMENT_M = 0.250
LIDAR_DMAX_MM = 3000.0

VITESSE_AUTO_MIN_M_S = 0.0
VITESSE_AUTO_MAX_M_S = 0.6

BOUCLE_PERIODE_S = 0.01
AUTO_DEBUG = True

SEUIL_V_BLOCAGE_M_S = 0.02

# CAMERA
CAMERA_ACTIVE = True
CAMERA_WIDTH = 128
CAMERA_HEIGHT = 96
CAMERA_SHOW_WINDOW = False

CAMERA_BAND_RATIO = 0.30
CAMERA_MIN_RATIO = 0.03
CAMERA_DOMINANCE = 1.15
CAMERA_UNKNOWN_VALUE = -1

# SORTIE DE BLOCAGE
SECURITE_FRONT_FENETRE_DEG = 4
SECURITE_FRONT_MIN_POINTS = 5
SEUIL_FRONT_DEGAGEMENT_MM = 500.0

# AUTOMATE DE RECUL
SEUIL_ARRIERE_DEGAGEMENT_MM = 100.0

ANGLE_RECUL_FIXE_DEG = 18.0
VITESSE_BLOCAGE_M_S = 3
VITESSE_TURN_BLOCAGE_M_S = 0.5
BLOCAGE_ACTION_DURATION_S = 0.04

# DEBUG
DEBUG_ACTIONNEURS = True
DEBUG_LIDAR_RAW = True
DEBUG_PRINT_PERIOD_S = 0.5